// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://outngvycajxdgyellntw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91dG5ndnljYWp4ZGd5ZWxsbnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDkxMDYsImV4cCI6MjA3MTY4NTEwNn0.fENqexJazDKGTBzLvZARrDaPHNMZolfd1QvuyI18m7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});